@extends("la.layouts.app")

@section("contentheader_title")
	<a href="{{ url(config('laraadmin.adminRoute') . '/checklists') }}">Checklist</a> :
@endsection
@section("contentheader_description", $checklist->$view_col)
@section("section", "Checklists")
@section("section_url", url(config('laraadmin.adminRoute') . '/checklists'))
@section("sub_section", "Edit")

@section("htmlheader_title", "Checklists Edit : ".$checklist->$view_col)

@section("main-content")

@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="box">
	<div class="box-header">
		
	</div>
	<div class="box-body">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				{!! Form::model($checklist, ['route' => [config('laraadmin.adminRoute') . '.checklists.update', $checklist->id ], 'method'=>'PUT', 'id' => 'checklist-edit-form']) !!}
					@la_form($module)
					
					{{--
					@la_input($module, 'sucursal_id')
					@la_input($module, 'fecha')
					@la_input($module, 'fachada1')
					@la_input($module, 'ponderaconfachada1')
					@la_input($module, 'comentarios')
					@la_input($module, 'imagenfachada1')
					@la_input($module, 'fachada2')
					@la_input($module, 'ponderacionfachada2')
					@la_input($module, 'comentarios2')
					@la_input($module, 'imagen2')
					@la_input($module, 'fachada3')
					@la_input($module, 'ponderacionfachada3')
					@la_input($module, 'comentarios3')
					@la_input($module, 'imagen3')
					@la_input($module, 'fachada4')
					@la_input($module, 'ponderacion4')
					@la_input($module, 'comentarios4')
					@la_input($module, 'imagen4')
					@la_input($module, 'fachada5')
					@la_input($module, 'ponderacion5')
					@la_input($module, 'comentarios5')
					@la_input($module, 'imagen5')
					@la_input($module, 'fachada6')
					@la_input($module, 'ponderacionfachada6')
					@la_input($module, 'comentarios6')
					@la_input($module, 'imagen6')
					@la_input($module, 'imagenpregunta1')
					@la_input($module, 'ponderacion7')
					@la_input($module, 'comentarios7')
					@la_input($module, 'imagen7')
					@la_input($module, 'imagenpregunta2')
					@la_input($module, 'ponderacion8')
					@la_input($module, 'comentarios8')
					@la_input($module, 'imagen8')
					@la_input($module, 'imagenpregunta3')
					@la_input($module, 'ponderacion9')
					@la_input($module, 'comentarios9')
					@la_input($module, 'imagen9')
					@la_input($module, 'imagenpregunta4')
					@la_input($module, 'ponderacion10')
					@la_input($module, 'comentarios10')
					@la_input($module, 'imagen10')
					@la_input($module, 'imagenpregunta5')
					@la_input($module, 'ponderacion11')
					@la_input($module, 'comentarios11')
					@la_input($module, 'imagen11')
					@la_input($module, 'imagenpregunta6')
					@la_input($module, 'ponderacion12')
					@la_input($module, 'comentarios12')
					@la_input($module, 'imagen12')
					@la_input($module, 'imagenpregunta7')
					@la_input($module, 'ponderacion13')
					@la_input($module, 'comentarios13')
					@la_input($module, 'imagen13')
					@la_input($module, 'imagenpregunta8')
					@la_input($module, 'ponderacion14')
					@la_input($module, 'comentarios14')
					@la_input($module, 'imagen14')
					@la_input($module, 'imagenpregunta9')
					@la_input($module, 'ponderacion15')
					@la_input($module, 'comentarios15')
					@la_input($module, 'imagen15')
					@la_input($module, 'recepcion1')
					@la_input($module, 'ponderacion16')
					@la_input($module, 'comentarios16')
					@la_input($module, 'imagen16')
					@la_input($module, 'recepcion2')
					@la_input($module, 'ponderacion17')
					@la_input($module, 'comentarios17')
					@la_input($module, 'imagen17')
					@la_input($module, 'recepcion3')
					@la_input($module, 'ponderacion18')
					@la_input($module, 'comentarios18')
					@la_input($module, 'imagen18')
					@la_input($module, 'recepcion4')
					@la_input($module, 'ponderacion19')
					@la_input($module, 'comentarios19')
					@la_input($module, 'imagen19')
					@la_input($module, 'recepcion5')
					@la_input($module, 'ponderacion20')
					@la_input($module, 'comentarios20')
					@la_input($module, 'imagen20')
					@la_input($module, 'recepcion6')
					@la_input($module, 'ponderacion21')
					@la_input($module, 'comentarios21')
					@la_input($module, 'imagen21')
					@la_input($module, 'recepcion7')
					@la_input($module, 'ponderacion22')
					@la_input($module, 'comentarios22')
					@la_input($module, 'imagen22')
					@la_input($module, 'recepcion8')
					@la_input($module, 'ponderacion23')
					@la_input($module, 'comentarios23')
					@la_input($module, 'imagen23')
					@la_input($module, 'cubiculo1')
					@la_input($module, 'ponderacion24')
					@la_input($module, 'comentarios24')
					@la_input($module, 'imagen24')
					@la_input($module, 'cubiculo2')
					@la_input($module, 'ponderacion25')
					@la_input($module, 'comentarios25')
					@la_input($module, 'imagen25')
					@la_input($module, 'cubiculo3')
					@la_input($module, 'ponderacion26')
					@la_input($module, 'comentarios26')
					@la_input($module, 'imagen26')
					@la_input($module, 'cubiculo4')
					@la_input($module, 'ponderacion27')
					@la_input($module, 'comentarios27')
					@la_input($module, 'imagen27')
					@la_input($module, 'cubiculo5')
					@la_input($module, 'ponderacion28')
					@la_input($module, 'comentarios28')
					@la_input($module, 'imagen28')
					@la_input($module, 'cubiculo6')
					@la_input($module, 'ponderacion29')
					@la_input($module, 'comentarios29')
					@la_input($module, 'imagen29')
					@la_input($module, 'cubiculo7')
					@la_input($module, 'ponderacion30')
					@la_input($module, 'comentarios30')
					@la_input($module, 'imagen30')
					@la_input($module, 'cubiculo8')
					@la_input($module, 'ponderacion31')
					@la_input($module, 'comentarios31')
					@la_input($module, 'imagen31')
					@la_input($module, 'proceso1')
					@la_input($module, 'ponderacion32')
					@la_input($module, 'comentarios32')
					@la_input($module, 'proceso2')
					@la_input($module, 'ponderacion33')
					@la_input($module, 'comentarios33')
					@la_input($module, 'proceso3')
					@la_input($module, 'ponderacion34')
					@la_input($module, 'comentarios34')
					@la_input($module, 'proceso4')
					@la_input($module, 'ponderacion35')
					@la_input($module, 'comentarios35')
					@la_input($module, 'proceso5')
					@la_input($module, 'ponderacion36')
					@la_input($module, 'comentarios36')
					@la_input($module, 'imagen36')
					@la_input($module, 'proceso6')
					@la_input($module, 'ponderacion37')
					@la_input($module, 'comentarios37')
					@la_input($module, 'proceso7')
					@la_input($module, 'ponderacion38')
					@la_input($module, 'comentarios38')
					@la_input($module, 'archivo1')
					@la_input($module, 'proceso8')
					@la_input($module, 'ponderacion39')
					@la_input($module, 'comentarios39')
					@la_input($module, 'archivo2')
					@la_input($module, 'proceso9')
					@la_input($module, 'ponderacion40')
					@la_input($module, 'comentarios40')
					@la_input($module, 'archivo3')
					@la_input($module, 'proceso10')
					@la_input($module, 'ponderacion41')
					@la_input($module, 'comentarios41')
					@la_input($module, 'archivo4')
					@la_input($module, 'proceso11')
					@la_input($module, 'ponderacion42')
					@la_input($module, 'comentarios42')
					@la_input($module, 'proceso12')
					@la_input($module, 'ponderacion43')
					@la_input($module, 'comentarios43')
					@la_input($module, 'proceso13')
					@la_input($module, 'ponderacion44')
					@la_input($module, 'comentarios44')
					@la_input($module, 'inventario1')
					@la_input($module, 'ponderacion45')
					@la_input($module, 'comentarios45')
					@la_input($module, 'imagen45')
					@la_input($module, 'inventario2')
					@la_input($module, 'ponderacion46')
					@la_input($module, 'comentarios46')
					@la_input($module, 'imagen46')
					@la_input($module, 'sistema4')
					@la_input($module, 'ponderacion47')
					@la_input($module, 'comentarios47')
					@la_input($module, 'imagen47')
					@la_input($module, 'sistema3')
					@la_input($module, 'ponderacion48')
					@la_input($module, 'comentarios48')
					@la_input($module, 'imagen48')
					@la_input($module, 'sistema2')
					@la_input($module, 'ponderacion49')
					@la_input($module, 'comentarios49')
					@la_input($module, 'imagen49')
					@la_input($module, 'sistema1')
					@la_input($module, 'ponderacion50')
					@la_input($module, 'comentarios50')
					@la_input($module, 'imagen50')
					@la_input($module, 'calfinal')
					@la_input($module, 'video')
					--}}
                    <br>
					<div class="form-group">
						{!! Form::submit( 'Update', ['class'=>'btn btn-success']) !!} <button class="btn btn-default pull-right"><a href="{{ url(config('laraadmin.adminRoute') . '/checklists') }}">Cancel</a></button>
					</div>
				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>

@endsection

@push('scripts')
<script>
$(function () {
	$("#checklist-edit-form").validate({
		
	});
});
</script>
@endpush
